name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: dart-lang/setup-flutter@v1
        with:
          channel: stable  # Explicitly specify the stable channel
          
      - name: Check Flutter Environment
        run: flutter doctor -v

      - name: List Directory Contents
        run: dir
        working-directory: unit_test

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run Tests
        run: flutter test
        working-directory: unit_test