name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test  # Points to the Flutter project

      - name: Run Tests
        run: flutter test
        working-directory: unit_test  # Runs tests inside the Flutter project
