name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v1.6.0  # Verified working version
        with:
          channel: stable

      - name: Verify Flutter
        run: flutter doctor -v

      - name: List Directory Contents
        run: dir
        working-directory: unit_test  # Verify this path exists

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run Tests
        run: flutter test
        working-directory: unit_test