name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Use the stable version unless you need dev

      - name: Navigate to Flutter Project
        run: cd unit_test

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test  # Add this to specify the directory

      - name: Run Tests
        run: flutter test
        working-directory: unit_test  # Add this to specify the directory
