name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: dart-lang/setup-flutter@v2.0.0  # Verified working version
        with:
          channel: stable
          architecture: x64  # Explicitly specify for Windows

      - name: Verify Paths
        run: |
          cd unit_test
          dir
          flutter --version

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run Tests
        run: flutter test
        working-directory: unit_test