name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Try with 'stable' first
          cache: true  # Enable caching to improve performance

      - name: Force Flutter Upgrade
        run: flutter upgrade

      - name: Check Flutter Version
        run: flutter --version

      - name: List Directory Contents
        run: dir
        working-directory: unit_test

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run Tests
        run: flutter test
        working-directory: unit_test
