name: Flutter CI Demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64  # Explicit architecture

      - name: Verify Project Structure
        run: |
          cd unit_test
          flutter --version
          ls -la

      - name: Install dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run tests
        run: flutter test
        working-directory: unit_test