name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-flutter@v2
        with:
          channel: stable  # Add Flutter channel specification

      - name: Install dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run tests
        run: flutter test
        working-directory: unit_test