name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Switch to Windows runner
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: List Directory Contents
        run: dir
        working-directory: unit_test  # Check if the Flutter project is visible

      - name: Check pubspec.yaml Presence
        run: dir pubspec.yaml
        working-directory: unit_test  # Ensure pubspec.yaml is in unit_test

      - name: Install Dependencies
        run: flutter pub get
        working-directory: unit_test

      - name: Run Tests
        run: flutter test
        working-directory: unit_test
